#.bashrc
# Determine what (Bourne compatible) shell we are running under. Put the result
# in $PROFILE_SHELL (not $SHELL) so further code can depend on the shell type.
if test -n "$ZSH_VERSION"; then
  PROFILE_SHELL=zsh
elif test -n "$BASH_VERSION"; then
  PROFILE_SHELL=bash
elif test -n "$KSH_VERSION"; then
  PROFILE_SHELL=ksh
else
  PROFILE_SHELL=sh
fi

# source fzf - cli fuzzy finder for VIM
if [ $PROFILE_SHELL = "zsh" ]; then
	[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
elif [ $PROFILE_SHELL = "bash" ]; then
	[ -f ~/.fzf.bash ] && source ~/.fzf.bash
fi
