if [ -e ~/.bashrc ]; then
    source ~/.bashrc
fi

# >>> coursier install directory >>>
export PATH="$PATH:/Users/michael_sestito/Library/Application Support/Coursier/bin"
# <<< coursier install directory <<<
